import sys

def patch_file(path, edits):
    with open(path,'r',encoding='utf-8',newline='') as f:
        data=f.read()
    for old,new in edits:
        if new in data and old not in data:
            print('skip'); continue
        if old not in data:
            print('ANCHOR NOT FOUND',repr(old[:60])); sys.exit(1)
        if data.count(old)!=1:
            print('NOT UNIQUE',data.count(old)); sys.exit(1)
        data=data.replace(old,new); print('ok',repr(old[:34]))
    with open(path,'w',encoding='utf-8',newline='') as f:
        f.write(data)

SRC_EDITS = [
    ("function _recParseText(text){\n  var NL=String.fromCharCode(10);\n  var lines=String(text||'').split(NL);\n  var blocks=[]; var cur=null; var bodyMode=false;\n  for(var i=0;i<lines.length;i++){\n    var rawLine=String(lines[i]==null?'':lines[i]);\n    var line=rawLine.trim();\n    var mk=line.match(/^===\\s*\\[([^\\]]*)\\]\\s*(.*?)\\s*===$/);\n    if(mk){\n      if(cur) blocks.push(cur);\n      cur={ idRaw:String(mk[1]||'').trim(), nameRaw:String(mk[2]||'').trim(), title:'', day:'', subject:'', unit:'', body:'' };\n      bodyMode=false; continue;\n    }\n    if(!cur) continue;\n    if(!bodyMode){\n      var ci=line.indexOf('：'); if(ci<0) ci=line.indexOf(':');\n      var k=(ci>=0)?line.slice(0,ci).replace(/[ \u3000]/g,''):'';\n      var v=(ci>=0)?line.slice(ci+1).trim():'';\n      if(k.indexOf('タイトル')>=0||k.indexOf('題名')>=0){ cur.title=v; continue; }\n      if(k.indexOf('日付')>=0||k.indexOf('日時')>=0||k.indexOf('実施日')>=0){ cur.day=_recHalfDate(v); continue; }\n      if(k.indexOf('教科')>=0||k.indexOf('科目')>=0){ cur.subject=v; continue; }\n      if(k.indexOf('単元')>=0){ cur.unit=v; continue; }\n      if(k.indexOf('本文')>=0||k.indexOf('内容')>=0){ bodyMode=true; if(v){ cur.body+=v; } continue; }\n      continue;\n    } else { cur.body += (cur.body?NL:'') + rawLine; }\n  }\n  if(cur) blocks.push(cur);\n  for(var b=0;b<blocks.length;b++){ blocks[b].body=String(blocks[b].body||'').replace(/\\s+$/,''); }\n  return blocks;\n}",
     "function _recNormRank(v){ var s=String(v==null?'':v); if(s.indexOf('◎')>=0) return '◎'; if(s.indexOf('○')>=0||s.indexOf('〇')>=0) return '○'; if(s.indexOf('△')>=0) return '△'; var t=s.toUpperCase(); if(t.indexOf('A')>=0) return '◎'; if(t.indexOf('B')>=0) return '○'; if(t.indexOf('C')>=0) return '△'; return ''; }\nfunction _recParseText(text){\n  var NL=String.fromCharCode(10);\n  var lines=String(text||'').split(NL);\n  var blocks=[]; var cur=null; var sec=null;\n  for(var i=0;i<lines.length;i++){\n    var rawLine=String(lines[i]==null?'':lines[i]);\n    var line=rawLine.trim();\n    var mk=line.match(/^===\\s*\\[([^\\]]*)\\]\\s*(.*?)\\s*===$/);\n    if(mk){ if(cur) blocks.push(cur); cur={ idRaw:String(mk[1]||'').trim(), nameRaw:String(mk[2]||'').trim(), title:'', day:'', subject:'', unit:'', body:'', reflection:'', evalRank:'', evalComment:'' }; sec=null; continue; }\n    if(!cur) continue;\n    var ci=line.indexOf('：'); if(ci<0) ci=line.indexOf(':');\n    var handled=false;\n    if(ci>=0&&ci<=14){\n      var k=line.slice(0,ci).replace(/[ \u3000]/g,'');\n      var v=line.slice(ci+1).trim();\n      if(k.indexOf('タイトル')>=0||k.indexOf('題名')>=0){ cur.title=v; sec=null; handled=true; }\n      else if(k.indexOf('日付')>=0||k.indexOf('日時')>=0||k.indexOf('実施日')>=0){ cur.day=_recHalfDate(v); sec=null; handled=true; }\n      else if(k.indexOf('教科')>=0||k.indexOf('科目')>=0){ cur.subject=v; sec=null; handled=true; }\n      else if(k.indexOf('単元')>=0){ cur.unit=v; sec=null; handled=true; }\n      else if(k.indexOf('評価コメント')>=0||k.indexOf('評価メモ')>=0){ cur.evalComment=v; sec='evalComment'; handled=true; }\n      else if(k.indexOf('評価')>=0){ cur.evalRank=_recNormRank(v); sec=null; handled=true; }\n      else if(k.indexOf('振り返り')>=0||k.indexOf('ふりかえり')>=0){ sec='reflection'; if(v){ cur.reflection+=v; } handled=true; }\n      else if(k.indexOf('本文')>=0||k.indexOf('内容')>=0||k.indexOf('成果物')>=0){ sec='body'; if(v){ cur.body+=v; } handled=true; }\n    }\n    if(handled) continue;\n    if(sec==='body'){ cur.body += (cur.body?NL:'') + rawLine; }\n    else if(sec==='reflection'){ cur.reflection += (cur.reflection?NL:'') + rawLine; }\n    else if(sec==='evalComment'){ cur.evalComment += (cur.evalComment?NL:'') + rawLine; }\n  }\n  if(cur) blocks.push(cur);\n  for(var b=0;b<blocks.length;b++){ blocks[b].body=String(blocks[b].body||'').replace(/\\s+$/,''); blocks[b].reflection=String(blocks[b].reflection||'').replace(/\\s+$/,''); blocks[b].evalComment=String(blocks[b].evalComment||'').replace(/\\s+$/,''); }\n  return blocks;\n}"),
]

patch_file('src/index.tsx', SRC_EDITS)
print('DONE PB')
